---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Make sure swap space is created.
      ansible.builtin.debug:
        var: ansible_facts.swaptotal_mb

    - name: Check whether ruby is installed
      ansible.builtin.shell: |
        ruby --version
      register: ruby_installed
      changed_when: false

    - name: Make sure Ruby is installed
      ansible.builtin.debug:
        var: ruby_installed

    - name: Register results of showing configuration snippet command to variable
      ansible.builtin.command: passenger-install-apache2-module --snippet
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      register: passenger_snippet
      changed_when: passenger_snippet.rc == 0

    - name: Make sure passenger is installed.
      ansible.builtin.debug:
        var: passenger_snippet

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
